In [ ]:
import pandas as pd

In [2]:
import pandas as pd
AnimalsName = pd.Series(["Lion" , "Cat" ,"Dog" ,"Shephered"])
AnimalsName

0         Lion
1          Cat
2          Dog
3    Shephered
dtype: str

In [3]:
carColour = pd.Series(["Black", "Red" ,"White" ,"Pink"])
carColour

0    Black
1      Red
2    White
3     Pink
dtype: str

In [4]:
carColour = pd.Series([1,4,5,7,2])
carColour

0    1
1    4
2    5
3    7
4    2
dtype: int64

In [6]:
print(carColour.dtype)
print()
print(carColour.shape)
print()
print(carColour.size)
print()

int64

(5,)

5

In [7]:
carColour.isna().sum()

np.int64(0)

In [9]:
carColour.info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [5]:
carColour.loc[2:3]

2    5
3    7
dtype: int64

In [35]:
import pandas as pd


Details = {
    'Name': ['Arun', 'Anu', 'Rahul'],
    'Age': [20, 21, 22],
    'Mark': [85, 90, 78]
}

details = pd.DataFrame(Details)


print(details)

    Name  Age  Mark
0   Arun   20    85
1    Anu   21    90
2  Rahul   22    78

In [14]:
Fruits = pd.Series(['Orange','Apple' ,'Banana','Grapes'] ,index = [2,3,4,1])
Fruits

2    Orange
3     Apple
4    Banana
1    Grapes
dtype: str

In [12]:
Fruits.loc[2:3]

NameError: name 'Fruits' is not defined

In [15]:
Fruits.loc[1]

'Grapes'

In [11]:
Fruits.notna().sum()

NameError: name 'Fruits' is not defined

In [12]:
studname = pd.Series(["peter","parker","steve","rogers"])
studroll=pd.Series([1,2,3,4])
data={
    "student":studname,
    "roll":studroll
}
stddata=pd.DataFrame(data)
print(stddata)

  student  roll
0   peter     1
1  parker     2
2   steve     3
3  rogers     4

In [14]:
df = pd.read_csv("C:\\Users\\DELL\\Downloads\\Python_Learning\\karu.csv")
df

   S.No     Name  Age    City
0     1  Karunya   22  London

In [19]:
df.to_csv("Test.cv",index = "False")

In [20]:
newdf = pd.read_csv("Test.cv")
print(newdf)

   Unnamed: 0  S.No     Name  Age    City
0           0     1  Karunya   22  London

In [21]:
print(newdf.dtypes)

Unnamed: 0    int64
S.No          int64
Name            str
Age           int64
City            str
dtype: object

In [22]:
newdf.describe()

       Unnamed: 0  S.No   Age
count         1.0   1.0   1.0
mean          0.0   1.0  22.0
std           NaN   NaN   NaN
min           0.0   1.0  22.0
25%           0.0   1.0  22.0
50%           0.0   1.0  22.0
75%           0.0   1.0  22.0
max           0.0   1.0  22.0

In [26]:
### *Head and Tail*

newdf.head(3)

   Unnamed: 0  S.No     Name  Age    City
0           0     1  Karunya   22  London

In [25]:
newdf.tail()

   Unnamed: 0  S.No     Name  Age    City
0           0     1  Karunya   22  London

In [27]:
#loc and iloc

newdf.loc[0]

Unnamed: 0          0
S.No                1
Name          Karunya
Age                22
City           London
Name: 0, dtype: object

In [ ]:
#columns